/**
 * The spoken channel's runtime (#163 §4) — the per-device toggle, the manifest, and
 * the sink's registration.
 *
 * Voice is a TOGGLE; text is not. The pref persists per device (localStorage), like
 * the other trainer tooling prefs. The clip manifest (`public/voice/manifest.json`,
 * generated by `npm run voice`) is fetched once, lazily, the first time the trainer
 * is opened; until it arrives — or if it never does — the sink has no clips and says
 * nothing, and the written channel carries on.
 *
 * `installVoice()` is idempotent and is called from the Trainer panel's mount, so the
 * spoken channel is reachable exactly where the trainer is.
 */
import { create } from 'zustand';
import { createJSONStorage, persist, type StateStorage } from 'zustand/middleware';
import { addGuidanceSink } from './guidance';
import { clipFor, type VoiceManifest } from './speakable';
import { createAudioElementPlayer, createVoiceSink, type AudioElementPlayer, type VoiceSink } from './voice';

// localStorage in the browser; a no-op elsewhere (the Node test runtime), so the
// persist middleware never warns about a missing window (the same guard as store.ts).
const noopStorage: StateStorage = { getItem: () => null, setItem: () => undefined, removeItem: () => undefined };
const prefStorage = (): StateStorage => (typeof window !== 'undefined' && window.localStorage ? window.localStorage : noopStorage);

interface VoiceState {
  enabled: boolean;
  setEnabled(on: boolean): void;
}

/** The per-device "say the instructions out loud" pref. */
export const useVoice = create<VoiceState>()(
  persist((set) => ({ enabled: false, setEnabled: (on) => set({ enabled: on }) }), {
    name: 'thoremin-trainer-voice',
    storage: createJSONStorage(prefStorage),
  }),
);

interface VoiceManifestState {
  /** The loaded manifest, or null before it arrives / when unavailable. */
  manifest: VoiceManifest | null;
  /** Whether `text` has a clip. False until the manifest is loaded. */
  hasClip(text: string): boolean;
}

/** The loaded clip set, for React: the picker marks cues that would be text-only. */
export const useVoiceManifest = create<VoiceManifestState>()((_set, get) => ({
  manifest: null,
  hasClip: (text) => {
    const m = get().manifest;
    return !!m && clipFor(m, text) !== null;
  },
}));

/** The one audio element the default player reuses (see voice.ts on autoplay). */
const audioPlayer: AudioElementPlayer = createAudioElementPlayer();

/** Call inside a user gesture (the voice toggle's click): lifts the autoplay gate. */
export function unlockVoice(): void {
  audioPlayer.unlock();
}

/** Where the clips live, relative to the app's base URL. */
export const VOICE_DIR = 'voice/';

let sink: VoiceSink | null = null;
let installed = false;

/** Resolve a path under the app's base (Vite's `BASE_URL`, e.g. `/thoremin/`). */
function underBase(path: string): string {
  const base = (import.meta as unknown as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/';
  return `${base.endsWith('/') ? base : `${base}/`}${path}`;
}

/** Fetch the manifest; null when unavailable (no server, not generated, offline). */
export async function loadVoiceManifest(fetchImpl: typeof fetch = fetch): Promise<VoiceManifest | null> {
  try {
    // The manifest is the one MUTABLE url in the clip set (the clips are content-
    // addressed and immutable) and the server sends no Cache-Control: ask the browser
    // to revalidate (one conditional request per page load, a 304 when unchanged)
    // rather than trust heuristic freshness — otherwise a regenerated set could go
    // silent until the cache expired.
    const res = await fetchImpl(underBase(`${VOICE_DIR}manifest.json`), { cache: 'no-cache' });
    if (!res.ok) return null;
    const json = (await res.json()) as VoiceManifest;
    return json && typeof json === 'object' && json.clips ? json : null;
  } catch {
    return null;
  }
}

/**
 * Register the voice sink (once) and keep its enabled flag in step with the pref.
 * Safe to call on every panel mount.
 */
export function installVoice(): void {
  if (installed) return;
  installed = true;
  void loadVoiceManifest().then((manifest) => {
    if (!manifest) {
      // Unavailable now (offline, not generated): try again on the next panel open
      // rather than leaving voice dead for the page's lifetime.
      installed = false;
      return;
    }
    useVoiceManifest.setState({ manifest });
    sink = createVoiceSink({ manifest, baseUrl: underBase(VOICE_DIR), player: audioPlayer.play, enabled: useVoice.getState().enabled });
    addGuidanceSink(sink);
    useVoice.subscribe((s) => sink?.setEnabled(s.enabled));
  });
}

/** For tests. */
export function resetVoiceRuntime(): void {
  installed = false;
  sink = null;
  useVoiceManifest.setState({ manifest: null });
}
