/**
 * The spoken channel's runtime (#163 §4) — the per-device toggle, the manifest, and
 * the sink's registration.
 *
 * Voice is a TOGGLE; text is not. The pref persists per device (localStorage), like
 * the other trainer tooling prefs. The clip manifest (`public/voice/manifest.json`,
 * generated by `npm run voice`) is fetched once, lazily, the first time the trainer
 * is opened; until it arrives — or if it never does — the sink has no clips and says
 * nothing, and the written channel carries on.
 *
 * `installVoice()` is idempotent and is called from the Trainer panel's mount, so the
 * spoken channel is reachable exactly where the trainer is.
 */
import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { addGuidanceSink } from './guidance';
import type { VoiceManifest } from './speakable';
import { createVoiceSink, type VoiceSink } from './voice';

interface VoiceState {
  enabled: boolean;
  setEnabled(on: boolean): void;
}

/** The per-device "say the instructions out loud" pref. */
export const useVoice = create<VoiceState>()(
  persist((set) => ({ enabled: false, setEnabled: (on) => set({ enabled: on }) }), {
    name: 'thoremin-trainer-voice',
  }),
);

interface VoiceManifestState {
  /** The loaded manifest, or null before it arrives / when unavailable. */
  manifest: VoiceManifest | null;
  /** Whether `text` has a clip. False until the manifest is loaded. */
  hasClip(text: string): boolean;
}

/** The loaded clip set, for React: the picker marks cues that would be text-only. */
export const useVoiceManifest = create<VoiceManifestState>()((_set, get) => ({
  manifest: null,
  hasClip: (text) => !!get().manifest?.clips[text],
}));

/** Where the clips live, relative to the app's base URL. */
export const VOICE_DIR = 'voice/';

let sink: VoiceSink | null = null;
let installed = false;

/** Resolve a path under the app's base (Vite's `BASE_URL`, e.g. `/thoremin/`). */
function underBase(path: string): string {
  const base = (import.meta as unknown as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/';
  return `${base.endsWith('/') ? base : `${base}/`}${path}`;
}

/** Fetch the manifest; null when unavailable (no server, not generated, offline). */
export async function loadVoiceManifest(fetchImpl: typeof fetch = fetch): Promise<VoiceManifest | null> {
  try {
    const res = await fetchImpl(underBase(`${VOICE_DIR}manifest.json`));
    if (!res.ok) return null;
    const json = (await res.json()) as VoiceManifest;
    return json && typeof json === 'object' && json.clips ? json : null;
  } catch {
    return null;
  }
}

/**
 * Register the voice sink (once) and keep its enabled flag in step with the pref.
 * Safe to call on every panel mount.
 */
export function installVoice(): void {
  if (installed) return;
  installed = true;
  void loadVoiceManifest().then((manifest) => {
    if (!manifest) return;
    useVoiceManifest.setState({ manifest });
    sink = createVoiceSink({ manifest, baseUrl: underBase(VOICE_DIR), enabled: useVoice.getState().enabled });
    addGuidanceSink(sink);
    useVoice.subscribe((s) => sink?.setEnabled(s.enabled));
  });
}

/** For tests. */
export function resetVoiceRuntime(): void {
  installed = false;
  sink = null;
  useVoiceManifest.setState({ manifest: null });
}
